### ISSUE TITLE
Sort out test infrastructure for OCS v1 and v2 requests

### ISSUE THREAD

**Issue by phil-davis** [owncloud/owncloud-sdk#572]
for example:
```
    .then(() =>
      provider.addInteraction({
        uponReceiving: 'set user attribute of an existing user, attribute is allowed',
        withRequest: {
          method: 'PUT',
          path: Pact.Matchers.regex({
            matcher: '.*\\/ocs\\/v(1|2)\\.php\\/cloud\\/users\\/' + config.testUser,
            generate: '/ocs/v1.php/cloud/users/' + config.testUser
          }),
          headers: validAuthHeaders,
          body: 'key=email&value=asd%40a.com'
        },
        willRespondWith: {
          status: 200,
          headers: {
            'Access-Control-Allow-Origin': origin,
            'Content-Type': 'text/xml; charset=utf-8',
            'Access-Control-Allow-Methods': 'GET,OPTIONS,POST,PUT,DELETE,MKCOL,PROPFIND,PATCH,PROPPATCH,REPORT'
          },
          body: '<?xml version="1.0"?>\n' +
            '<ocs>\n' +
            ' <meta>\n' +
            '  <status>ok</status>\n' +
            '  <statuscode>100</statuscode>\n' +
            '  <message/>\n' +
            ' </meta>\n' +
            ' <data/>\n' +
            '</ocs>'
        }
      }))
```

A request can arrive to `ocs/v1.php` or `ocs/v2.php`. Both will respond with a body that includes in it `<statuscode>100</statuscode>`. But for `ocs/v2.php` the status code should be 200.

**Comment by dpakach** [comment]
@individual-it I dont think we really need this, since there is a verification happening after every tests and there is no way to set the ocs api version for the sdk, we can only really tests the api that the sdk uses. any thoughts?

**Comment by individual-it** [comment]
we have blindly putting in those regex in the contracts, and I think that was a mistake (of mine :see_no_evil: in the first place) 

we might get us in the situation where all tests pass but the server does not work together with the sdk.
This might happen

**during the tests:**
1. SDK sends request to `v2.php` endpoint
2. mock server replies with `statuscode=100`
3. SDK has a bug and expects wrongly `statuscode==100`
4. consumer tests pass
3. provider test sends request to `v1.php` (because of the `generate` part)
4. server replies correctly with `statuscode=100`
5. provider side tests pass also

**in real live:**
1. SDK sends request to `v2.php` endpoint on the real server
2. server replies correctly with `statuscode=200`
3. because of the SDK bug it expects wrongly `statuscode==100` and crashes

see also the example in this discussion https://github.com/pact-foundation/pact-js/issues/548#issuecomment-763358019

we should avoid having matchers in the requests.

@dpakach is completely right, we only can tests the api that the sdk uses, but we should adjust the contract, so that it only reflects the APIs that the SDK uses

**Comment by dpakach** [comment]
Removed v1/v2 wildcards from url in https://github.com/owncloud/owncloud-sdk/pull/717
